### ISSUE TITLE
用IPFS的pubsub功能替代MQTT

### ISSUE THREAD

**Issue by eos21** [yenkuanlee/IPDC#2]
新版的IPFS已经支持pubsub功能，IPDC的MQTT能不能用其pubsub替代？

**Comment by yenkuanlee** [comment]
您好
目前 pubsub 似乎在實驗階段
且 ipfs 的 python api 經測試後尚不穩定
因此暫不考慮替代

非常感謝您寶貴的意見
IPDC 會持續關注 pubsub 的發展
謝謝

**Comment by eos21** [comment]
你的工作很有趣，期待你IPDC的进一步完善。

**Comment by yenkuanlee** [comment]
感謝您的支持,

IPDC 會繼續努力前進！

我先將此 issue 關閉

再次感謝您.
